### ISSUE TITLE
Test can't run without Express installed.

### ISSUE THREAD

**Issue by mendelB** [learn-co-curriculum/angular-use-expressions-lab#2]
@ipc103 @AnnJohn @PeterBell 
Same issue as in the previous Angular labs that ran protractor, with `learn` not working without `express` installed.

**Comment by PeterBell** [comment]
Hey @mendelB LGTM. Going to merge this. Just revert it @ipc103 if you don't like it :)

**Comment by PeterBell** [comment]
Doh - see you just merged @ipc103  - sorry!
